[package]
name = "eggplant-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
eggplant-core = { path = "../eggplant-core" }
futures = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "blocking", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.9"
async-stream = "0.3"
async-trait = "0.1"
bytes = "1"
